server:
  port: 80
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    context-path: /Buyhere
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buyheredb?serverTimezone=Europe/Dublin
    username: root
    password: cj
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 781464605226-s2kqdhjjkg0fakribh1vamuq0qkb412n.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
  thymeleaf:
    mode: HTML5

